### PR TITLE
added pw reset token model

### LINKED ISSUE #52: Create PasswordResetToken Model

### PR DESCRIPTION
**Pull request by h-yung**
Closes #52

### CODE REVIEW

**Review by RDiMag — APPROVED** [review]

**Review by jpatrici — COMMENTED** [review]
hmm it's weird that there's 41 file changes 🤔 did you do `git pull --rebase` in branch 42 and then `git rebase <branch 42>` in your branch?

**Comment by h-yung** [comment]
@jpatrici weird indeed. I tried again - 
checked out 42- and did `git pull`
checked out 52- and did a rebase 42 in my branch

It should be ok this time...

**Review by jpatrici — COMMENTED** [review]
your change alone for the model is good 👍 but i'm not sure if merging this PR is going to be okay with all the other file changes 🤔 wouldnt it create a conflict? I feel like there's a disconnect somewhere

**Comment by h-yung** [comment]
Closing /replacing with new PR.

**Pull request closed without merging**
